version: '2'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guac
  guacd:
    image: glyptodon/guacd
    restart: always
    networks:
      - guac
  guac:
    image: glyptodon/guacamole
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - guac
    depends_on:
      - postgres
      - guacd

  webserver:
   image: httpd:2.4
   volumes:
    - $PWD/web/htdocs:/usr/local/apache2/htdocs
    - $PWD/web/conf:/usr/local/apache2/conf
    - $PWD/web/error:/usr/local/apache2/error
    - $PWD/web/logs:/usr/local/apache2/logs
   ports:
    - "80:80"
    
volumes:
  data:
    driver: local

networks:
  guac:
    driver: bridge
  webserver:
    driver: bridge
